#
# ref:
#   - https://github.com/avelino/awesome-go/blob/master/.codeclimate.yml
#

---
engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  gofmt:
    enabled: true
  govet:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - go
ratings:
  paths:
    - "**.go"
exclude_paths:
  - vendor/
