################################################################################################################
#
# ref:
#   - https://github.com/caddyserver/caddy/blob/master/.goreleaser.yml
#   - https://github.com/nats-io/nats-server/blob/master/.goreleaser.yml
#
################################################################################################################
