version: '3'

################################################################################################
#
# ref:
#   - https://taskfile.dev/#/usage
#
################################################################################################


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

#
# global env: https://taskfile.dev/#/usage?id=environment-variables
#
env:
  ENV1: testing-env

# env file:
dotenv:
  - .env

################################################################################################

#
# task groups: https://taskfile.dev/#/usage?id=task-directory
#
tasks:
  default:
    cmds:
      - task: init
      - task: tidy
      - task: run


  install:
    cmds:
      - brew install go
      - go install github.com/oligot/go-mod-upgrade

  init:
    cmds:
      - cp .env.local .env

  tidy:
    cmds:
      - go mod tidy -v

  ################################################################################################

  upgrade:all:
    cmds:
      - export GOPROXY=https://goproxy.cn; go-mod-upgrade

  upgrade:one:
    cmds:
      - export GOPROXY=https://goproxy.cn; go get -u -v ${GO_PKG_NAME}
      - task: tidy

  dep-check:
    cmds:
      - go mod graph

  test:
    cmds:
      - go test all

  ################################################################################################

  pull:
    cmds:
      - git config pull.rebase false
      - git pull

  push:
    cmds:
      - git push origin master --tags
